### PR TITLE
Setup Project

### PR DESCRIPTION
**Pull request by mohametalmeari**
- [ ] Setup Webpack
- [ ] Setup Linters
- [ ] Create HTML Layout

### CODE REVIEW

**Review by TadesseDev — CHANGES_REQUESTED** [review]
### Hi @mohametalmeari 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑🛑
yPkfDFf

- [ ] I see you have an empty readme file, This will affect your professionality as a developer. We need to use a professional readme file in all our projects and for that [Microverse provides a Readme template](https://github.com/microverseinc/readme-template) we can customize and use it. I suggest you do the same before the next review request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by topeogunleye** [comment]
@mohametalmeari, I'm currently reviewing your project. please can you update to the latest linters set-up. Maybe this will help fix the error.

**Comment by topeogunleye** [comment]
Hi @mohametalmeari, I have consulted with my colleague about the Lighthouse error that you are getting. He suggested that the best solution is to re setup linters for your project. Here are the steps that you need to follow:

- Go to the linters repository and download the latest version of the configuration files.
- Delete the linters folder and the .github folder from your GitHub repository and your local environment.
- Make sure that the linters checks are not showing on GitHub anymore.
- Set up linters again from scratch following the instructions in the README file of the [html-css-js linters repository](https://github.com/microverseinc/linters-config/tree/master/html-css-js).

I hope this helps you fix the Lighthouse error and pass the tests. Please let me know if you have any questions or issues. I'm here to help.😊

**Review by V-Blaze — COMMENTED** [review]
Hi @mohametalmeari  , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

dcentl8-9b96e129-9725-401b-ac34-2feb990202a0

## Invalid Code Review Request

## You have submitted a project, that doesn't have the linters running on pull request. I can see you deleted the `.github/workflows/linters.yml`, but as [topeogunleye](https://github.com/topeogunleye) suggested, he suggested you delete and start the linter setup from scratch following this [html-css-js linters repository](https://github.com/microverseinc/linters-config/tree/master/html-css-js). I'll suggest you follow the aforementioned repository and set up your linters as they are a requirement for any Microverse project. :smile: :wave: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by bobb-Rob — COMMENTED** [review]
Hi @mohametalmeari, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has lighthouse linter issues. I trust you will find the solution to this before the next review request submission. I tried to figure out the issue but I believe it is from your linter setup. Kindly ensure all is working. You can set up another repo just to be sure there is no issue with this particular repo.


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by topeogunleye — APPROVED** [review]
### **STATUS: APPROVED  ✔️** 
------
Hi @mohametalmeari,  

Your project is complete! Great job for nailing it right on the first attempt 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟

wiserhood-cheers

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Followed Git flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title :heavy_check_mark:

## [Optional] suggestions:
- [ ] Nice work on the setup! However, the branch name 'setup-feature' doesn't clearly indicate the specific feature or action being implemented. To maintain consistency and improve clarity, consider renaming the branch to something like 'feature/setUpLeaderboard'. This follows the convention of naming branches after the feature or action they represent. It helps everyone understand the purpose of the branch at a glance. Feel free to consider this suggestion for future pull requests. Keep up the great work!

- [ ]  Next time, and for future commits, I kindly suggest that you please make use of imperative mood in the subject line for your commit messages.
:x: Bad Commit Messages :x:
image

### ✔️ Good Commit Messages: ✔️
✔️  Add fix for dark mode toggle state
✔️  Update README file.
✔️  Add styles to h1.

- [ ] Please refer to this article: please read it and apply it in your work from now on: [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md);

 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear
Please, remember to tag @topeogunleye in your question so I can receive the notification

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
